name: norminette

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  norminette:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pip
      uses: BSFishy/pip-action@v1
      with:
        packages: norminette
        upgrade: true
    - name: Norminette version
      run: norminette --version
    - name: Check norme errors
      run: norminette ./libft ./include/libft.h
