name: build

on:
  push:
    branches:
      - main
    paths:
      - '**.c'
      - '**.h'
      - 'Makefile'
  pull_request:
    branches:
      - main
    paths:
      - '**.c'
      - '**.h'
      - 'Makefile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        sudo apt install -y clang-12 libxext-dev libbsd-dev libx11-6
        RUN git clone https://github.com/42Paris/minilibx-linux /tmp/libmlx
        make -C /tmp/libmlx
        mv /tmp/libmlx/libmlx.a /usr/local/lib/libmlx.a
        mv /tmp/libmlx/mlx.h /usr/local/include/mlx.h
    - name: GNU make version
      run: make --version
    - name: Build
      run: make